Added Validations for Team endpoints
1mac11/intelligence-manufacturing-system pull request #11
Opened 2022-06-20 04:59 UTC by 1mac11

2022-06-20 07:09 UTC, ahodkov requested changes
Better to use db optimization, because, for example, in update_team_check we call user at least twice(if team has 2 users) and call so many times for team database.

2022-06-20 07:09 UTC, ahodkov commented on core/utils/checkers.py
> +    check_managers(managers, team)
update and create has the same code, maybe, do you can add a new function for this?

2022-06-20 07:09 UTC, ahodkov commented on core/utils/checkers.py
> +        for worker in workers:
Also, you can use function:
```
def check_user(user, type_user):
    for user in users:
       if user.team.exists():
           raise ValidationError({type_user: f"{type_user} shouldn't be on other teams"})
```

2022-06-22 15:30 UTC, ahodkov approved these changes

2022-06-23 05:13 UTC, Zarif99 commented
merge

2022-06-23 05:14 UTC, merged